//===-- Passes.td - FIRRTL pass definition file ------------*- tablegen -*-===//
//
// This file contains definitions for passes that work on the FIRRTL dialect.
//
//===----------------------------------------------------------------------===//

#ifndef CIRCT_DIALECT_FIRRTL_PASSES_TD
#define CIRCT_DIALECT_FIRRTL_PASSES_TD

include "mlir/Pass/PassBase.td"

#endif // CIRCT_DIALECT_FIRRTL_PASSES_TD
